language: php
php:
- 7.1

before_install:
- nvm install

install:
- npm install
- npm run build

script:
- npm run test

cache:
  directories:
  - $HOME/.composer/cache/files

notifications:
  email:
    on_success: never
    on_failure: never
