on: push
name: Main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      uses: docker://basaltinc/docker-node-php-base:latest
      with:
        entrypoint: sh
        args: -c "npm install && composer install"
    - name: build
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build
    - name: docker://basaltinc/docker-node-php-base:latest
      uses: docker://basaltinc/docker-node-php-base:latest
      with:
        entrypoint: npm
        args: test
    - name: eslint
      uses: hallee/eslint-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: semantic release
      uses: docker://basaltinc/docker-node-php-base:latest
      if: github.ref == 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        entrypoint: npx
        args: semantic-release
